# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Blog
tagline:          blog too difficult
description:      "my blog"
url:              https://l4tt3.github.io/
baseurl:          /
                  # the optional subpath of your site, e.g. "/my-jekyll-site/"
                  # This will apply to all pages in your Jekyll site.

author:
  name:           L4tt3
  url:            https://www.fib-warning.tistory.com

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/my-jekyll-site/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            2.0.1

github:
  repo:             https://github.com/karloespiritu/blackdoc
